### ISSUE TITLE
About launch

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-main-2022#180]
- [x] Merge https://github.com/WordPress/wporg-mu-plugins/pull/329
- [x] Merge #178 
- [x] Deploy above
- [x] Merge and deploy #186 
- [x] Update #171 with custom font and merge 
- [x] Merge #176 
- [x] Commit change to add draft page to theme switcher
- [x] Deploy above changes
- [x] P2, Slack for feedback
- [x] Merge https://github.com/WordPress/wporg-parent-2021/pull/72
- [x] Update sub pages with list item spacing #189
- [x] Fix About landing page design and content tweaks #188
- [x] Merge #200
- [x] Merge #193 
- [x] Merge #201 
- [x] Deploy above
- [x] Get final sign-off
- [x] Merge [PR to update tools to live URLs](https://github.com/WordPress/wporg-main-2022/pull/183), and add SVN commit to add live page to theme switcher, then deploy
- [x] Deprecate existing live pages, rename drafts, and update menus used for navigation blocks
- [x] QA live page: links, responsive, Lighthouse audit

@bengreeley @jasmussen @tellyworth @eidolonnight

**Comment by adamwoodnz** [comment]
Lighthouse scores for landing page

| Desktop | Mobile |
|-|-|
| ![Screen Shot 2023-02-14 at 3 08 28 PM](https://user-images.githubusercontent.com/1017872/218620695-8d6acee5-3eae-42ca-9d87-564bbc491ee9.jpg) | ![Screen Shot 2023-02-14 at 3 08 57 PM](https://user-images.githubusercontent.com/1017872/218620729-ae148e99-8708-49c9-b6c2-68edf5434f4e.jpg) |
