### ISSUE TITLE
Overview Issue: General Elements of WP.org

### ISSUE THREAD

**Issue by pablohoneyhoney** [WordPress/wporg-main-2022#221]
This is an overview of all (identified) issues that relate to general, shared elements of the site, in particular in relation to the latest implementations, so we can refine them and scale them correctly to the rest. 

Mobile is indicated where applicable (tested in Safari, iPhone 12 Pro Max). When no indication, both desktop and mobile apply. Section and page specific notes coming up in their own overview issue. 

**Search**

- [x] Search and menu icons need to align in between states (resting, pressed), currently their position alter. Mobile and desktop. 
- [x] Search field remove UI (x) is out of place. Its position shall be more refined and aligned with the other icons. 
- [x] Align the different search fields across pages are using different icons and placeholder styles. 
- [x] The label can be more specific: _Search in WordPress_. Placeholder can be more suggestive of the behavior or as a paradigm. 
- [x] With Search open, if I scroll/swipe (which ideally I shouldn’t), the overlay breaks and the background scrolls. (https://github.com/WordPress/wporg-mu-plugins/issues/371)
- [x] We could also suggest the most searched terms. (discussed in https://github.com/WordPress/wporg-mu-plugins/issues/367 )

**Navigation**

- [x] When in subpages, the top nav highlights the main page. Worth removing to not mislead the user with wayfinding. 
- [x] (Mobile) _Get WP_ in menu panel is different than other buttons style. Worth aligning. 
- [x] (Mobile) _News_ is permanently underlined, even when other instances are active. 
- [x] When the specific page is white, the wayfinding doesn’t work and sections/pages aren’t marked. 
- [x] When in /developers for example, the nav changes slightly. 
- [x] (Mobile) Top bar nav is broken in /gutenberg.  WP logo differs in size, position, and shape from the normal nav in the rest of the site. 
- [ ]  (Mobile) When a category is active (ie:_Learn_), the whole category of nav instances move position.
- [ ] (Mobile) The behavior of active instances isn’t consistent (ie: _Get WP_ vs _Learn WP_). 
- [x] Ideally we signal what nav instances are external versus intrinsic to the site (with a timid arrow). Now they are mixed and there’s a harsh transition to certain properties (ie: Openverse). 
- [x] Logo shall have hover as well, and correct the one in /gutenberg. 
- [ ] There’s duplication of nav instances (ie: _Download&Extend_, _Get WP_, and _Get WP_), while the footer doesn’t have it. Worth revising through the IA exercise. 
- [ ] Certain instances are verbally obscure. Revise naming conventions (ie: _Mobile_ versus _Get Apps_ or _WordPress Apps_).
- [x] Dropdown shall have some bottom padding in the menu – when the last item is active it looks visually stressed.
- [x] The dropdown flyout is 1px off to the left.

**Footer**

- [x] Logo needs to align with social links vertically. 
- [x] (Mobile) Footer, in homepage: There’s a tall gap between CTA and footer links that can be a bit more conservative. 
- [ ] There’s a discrepancy between the top nav instances and the footer ones. It’s ok to have more footer but they are also grouped differently wich doesn’t help with a mental map. Some things are also called differently. (https://github.com/WordPress/wporg-mu-plugins/issues/364)
- [ ] We need to surface the categories in footer, or try to map them closer to the top nav system.  (https://github.com/WordPress/wporg-mu-plugins/issues/364)

**Login**

- [x] Top bar has a different color and styles (ie: hovers), worth exploring to integrate the register/log in instances better with the rest of the nav.  (https://github.com/WordPress/wporg-mu-plugins/issues/355)
- [x] Align styles of [https://login.wordpress.org] with the newer pages. (https://github.com/WordPress/wporg-main-2022/issues/241)

**Misc**

- [x] Highlight color text is in red/orange/coral #f86368 looks like wrongly alerting, too dark, and doesn’t have the links flipped to dark.   
- [x] In certain pages (especially when displaying older ones), top bar _Get WP_ hover state has a bug. 
- [ ] Headings and breadcrumbs and subnavs aren’t consistent or connected across pages. We’ll address these per section/page. 
- [x] There are inconsistencies in line heights and the formatting of typography that we’ll cover by section/page. 
- [x] The language banner, when multiple official languages are available in the locale, let’s list them equally, instead of parenthesis. And use the same capitalization (not consistent in Spain, for example).

**Comment by jasmussen** [comment]
Good summary. I'm extracting some individual issues and adding more context. Note that I'm not able to check the boxes or edit this issue, perhaps I need elevated permissions?

**Search**

* Align icons: https://github.com/WordPress/wporg-mu-plugins/issues/369 
* X to clear is out of place: https://github.com/WordPress/wporg-mu-plugins/issues/368
* Label, placeholder: https://github.com/WordPress/wporg-mu-plugins/issues/367 
* Align search inputs across the site: https://github.com/WordPress/wporg-main-2022/issues/228 

I was not able to reproduce this one:

> With Search open, if I scroll/swipe (which ideally I shouldn’t), the overlay breaks and the background scrolls.

**Comment by pablohoneyhoney** [comment]
Added a small one worth fixing related to the languages banner. 

And here's a recording of the Search overlay behavior issue in Safari. @jasmussen 

https://user-images.githubusercontent.com/25516611/227920703-11194390-3aab-49df-8617-08403b80cdaf.MOV

**Comment by jasmussen** [comment]
Ah, good one. Opened https://github.com/WordPress/wporg-mu-plugins/issues/371 for that one.

**Comment by jasmussen** [comment]
**Navigation**

* Remove navigation highlights when on subpages/posts, https://github.com/WordPress/wporg-mu-plugins/issues/370
* Align Get WP buttons between desktop and mobile: https://github.com/WordPress/wporg-mu-plugins/issues/363 
* News item always underlined: https://github.com/WordPress/wporg-mu-plugins/issues/372

**Comment by jasmussen** [comment]
>  When the specific page is white, the wayfinding doesn’t work and sections/pages aren’t marked.

Can you expand on this one? [Etiquette](https://wordpress.org/about/etiquette/) would be a good example. Etiquette is highlighted in the breadcrumbs, as is the main About parent. Per WordPress/wporg-mu-plugins#370 we can remove the latter. 

> When in /developers for example, the nav changes slightly.

Can you exand on this one as well?

> (Mobile) Top bar nav is broken in /gutenberg.  WP logo differs in size, position, and shape from the normal nav in the rest of the site.
>  Logo shall have hover as well, and correct the one in /gutenberg.

* Unify logo appearance, add hover style: WordPress/wporg-mu-plugins#366 
* Related: https://github.com/WordPress/wporg-gutenberg/issues/51

**Comment by jasmussen** [comment]
>  When in /developers for example, the nav changes slightly.
>   (Mobile) When a category is active (ie:Learn), the whole category of nav instances move position.

Potentially related, as compared to the homepage, these show the adminbar even when logged out. Created WordPress/wporg-mu-plugins#355 to suggest hiding the adminbar unless there's a good reason to show it.

**Comment by jasmussen** [comment]
>  (Mobile) The behavior of active instances isn’t consistent (ie: Get WP vs Learn WP).

Navigation: Active states isn’t consistent #358 

> Ideally we signal what nav instances are external versus intrinsic to the site (with a timid arrow). Now they are mixed and there’s a harsh transition to certain properties (ie: Openverse).

Navigation: Signal external links WordPress/wporg-mu-plugins#359

>  There’s duplication of nav instances (ie: Download&Extend, Get WP, and Get WP), while the footer doesn’t have it. Worth revising through the IA exercise.

and

> Certain instances are verbally obscure. Revise naming conventions (ie: Mobile versus Get Apps or WordPress Apps).

Navigation: Rephrase a few items, reconsider sorting WordPress/wporg-mu-plugins#360 

> Dropdown shall have some bottom padding in the menu – when the last item is active it looks visually stressed.
> The dropdown flyout is 1px off to the left.

Navigation: Refine and polish the dropdown menus WordPress/wporg-mu-plugins#361

**Comment by jasmussen** [comment]
**Footer**

> Logo needs to align with social links vertically.

Footer: Align logo with social links vertically WordPress/wporg-mu-plugins#362

> (Mobile) Footer, in homepage: There’s a tall gap between CTA and footer links that can be a bit more conservative.

Footer: Reduce gap between homepage CTA and footer WordPress/wporg-main-2022#239

> There’s a discrepancy between the top nav instances and the footer ones. It’s ok to have more footer but they are also grouped differently wich doesn’t help with a mental map. 
> Some things are also called differently.
> We need to surface the categories in footer, or try to map them closer to the top nav system.

Footer: Revisit footer links and categorize WordPress/wporg-mu-plugins#364

**Login**

> Top bar has a different color and styles (ie: hovers), worth exploring to integrate the register/log in instances better with the rest of the nav.

avigation: Hide the adminbar in most cases, explore how to better integrate the register/login links https://github.com/WordPress/wporg-mu-plugins/issues/355

Also related: Unify logo appearance and size, add hover style WordPress/wporg-mu-plugins#366

> Align styles of [https://login.wordpress.org] with the newer pages.

Login: Redesign the page WordPress/wporg-main-2022#241 — includes a first pass at the new visuals.

**Misc**

> Highlight color text is in red/orange/coral #f86368 looks like wrongly alerting, too dark, and doesn’t have the links flipped to dark.

Misc: Revisit the text highlight color WordPress/wporg-parent-2021#80

> In certain pages (especially when displaying older ones), top bar Get WP hover state has a bug.

Can you expand on this one? On which page are you seeing this?

<img width="302" alt="Screenshot 2023-03-28 at 14 33 01" src="https://user-images.githubusercontent.com/1204802/228237178-07d2be52-f582-493c-8193-9a0baec33a10.png">

> Headings and breadcrumbs and subnavs aren’t consistent or connected across pages. We’ll address these per section/page.

> There are inconsistencies in line heights and the formatting of typography that we’ll cover by section/page.

I haven't created a separate issue for these yet, I know we'll follow up with additional per-page issues and will be there for that.

> The language banner, when multiple official languages are available in the locale, let’s list them equally, instead of parenthesis. And use the same capitalization (not consistent in Spain, for example).

Language banner: list languages equally without parenthesis. WordPress/wporg-mu-plugins#365

**Comment by ryelle** [comment]
@jasmussen I think at this point, all of these issues have been fixed (except for [the iOS-specific search modal scrolling](https://github.com/WordPress/wporg-mu-plugins/issues/371)). Would you or someone else from @WordPress/meta-design be able to check over this issue to see if we can close it?

**Comment by fcoveram** [comment]
I see a draft state of [wporg-mu-plugins#382](https://github.com/WordPress/wporg-mu-plugins/pull/382) that seems to address the problem better. I'm not sure how to continue and give feedback @ryelle

**Comment by jasmussen** [comment]
> When the specific page is white, the wayfinding doesn’t work and sections/pages aren’t marked.

Coming [back to this one](https://github.com/WordPress/wporg-main-2022/issues/221#issuecomment-1485131278), I went ahead and checked the box as addressed. Let me know if that was in error. The parent page highlight has been fixed i https://github.com/WordPress/wporg-mu-plugins/issues/370.

I think there's still an ongoing issue, tracked mainly in https://github.com/WordPress/wporg-mu-plugins/issues/360, about whether the "Download & Extend" item should be highlighted when you are in the download section, or whether that should be extracted to be separate:

<img width="1392" alt="Screenshot 2023-04-26 at 13 53 36" src="https://user-images.githubusercontent.com/1204802/234568029-f974295a-87c1-4a73-805b-3f08dc1ca932.png">

There's still an issue related to the About page, which I opened separately here: #255

**Comment by jasmussen** [comment]
>  When in /developers for example, the nav changes slightly.

I checked this box, but with the caveat that there are some followup adminbar questions in https://github.com/WordPress/wporg-mu-plugins/issues/355#issuecomment-1523342235

**Comment by jasmussen** [comment]
>  (Mobile) Top bar nav is broken in /gutenberg.  WP logo differs in size, position, and shape from the normal nav in the rest of the site.

I checked this box, with the caveat that I found a new issue on this page, when logged in and on mobile. But I've added that to [the main issue for the Gutenberg header](https://github.com/WordPress/wporg-gutenberg/issues/55).

In other words, it's not addressed, but it's tracked separately.

**Comment by jasmussen** [comment]
>  (Mobile) When a category is active (ie:Learn), the whole category of nav instances move position.

Given recent changes to ancestor or taxonomy highlights, I'm not sure if I'm entirely capturing this one. But a few things come to mind. When learn is active, both the top level learn, and the first menu item are active, and there's a big left border:

<img width="452" alt="Screenshot 2023-04-26 at 14 49 37" src="https://user-images.githubusercontent.com/1204802/234580101-408367f2-57f3-405f-8df8-f05fc8f4d4b9.png">

Compare that with when another sub item is active:

<img width="384" alt="Screenshot 2023-04-26 at 14 48 08" src="https://user-images.githubusercontent.com/1204802/234580225-c338b8be-87b8-4a03-8175-e8b427ce053c.png">

For me personally, I'm drawn to the latter, especially on mobile. That is, removing the left border to indicate the ancestor, primarily, and then mainly highlighting the child item. 

It also overlaps a bit, I think, with this one:

> (Mobile) The behavior of active instances isn’t consistent (ie: Get WP vs Learn WP).

<img width="443" alt="Screenshot 2023-04-26 at 14 49 14" src="https://user-images.githubusercontent.com/1204802/234580452-434c843f-05f1-4d55-af53-9053c9243c53.png">

I keep pointing to https://github.com/WordPress/wporg-mu-plugins/issues/360 as a conversation on whether "Download & Extend" Should become just "Extend", and Download a separate item.

I also recall a conversation with @panchovm around how it might be useful to revisit these taxonomies and make them click-only menus. That is, the top level button does not take you to the "main" page for that section, it only opens the submenu. I.e. this:

![menu demo](https://user-images.githubusercontent.com/1204802/234581663-5f5c49a7-941c-417b-8f39-fc10b2068098.gif)

Should we open a new issue about this?

Edit: if we open a new issue, that might also be a way to address this one:

>  There’s duplication of nav instances (ie: Download&Extend, Get WP, and Get WP), while the footer doesn’t have it. Worth revising through the IA exercise.

**Comment by jasmussen** [comment]
Speaking of the mobile menu, I'm seeing the old dotted focus style when I initially open the menu on mobile:

<img width="388" alt="Screenshot 2023-04-26 at 14 57 54" src="https://user-images.githubusercontent.com/1204802/234581927-82199f10-1209-489a-8891-e8d1a64a9e58.png">

I would expect to see the new style, if any:

<img width="393" alt="Screenshot 2023-04-26 at 14 58 25" src="https://user-images.githubusercontent.com/1204802/234582066-01cec23f-b585-4c5c-ac96-23298d9a2a45.png">

**Comment by jasmussen** [comment]
> Logo shall have hover as well, and correct the one in /gutenberg.

I checked this one, even if the logo is still wrong in /gutenberg. I checked it because it's tracked in https://github.com/WordPress/wporg-gutenberg/issues/55, so we can fix it there and not let this thead be blocked from wrapping.

**Comment by jasmussen** [comment]
>  Certain instances are verbally obscure. Revise naming conventions (ie: Mobile versus Get Apps or WordPress Apps).

Stills says Mobile:

<img width="249" alt="Screenshot 2023-04-26 at 15 03 03" src="https://user-images.githubusercontent.com/1204802/234583316-9f55c546-14df-47d4-99b1-9e2bb5569bda.png">

I guess we can check it since it's tracked separately in https://github.com/WordPress/wporg-mu-plugins/issues/360. Let's just not forget it.

**Comment by jasmussen** [comment]
> In certain pages (especially when displaying older ones), top bar Get WP hover state has a bug.

Checked this one as I can't reproduce (anymore?)

That leaves us with this one:

> Headings and breadcrumbs and subnavs aren’t consistent or connected across pages. We’ll address these per section/page.

Related to https://github.com/WordPress/wporg-main-2022/issues/255, and perhaps we can evolve that issue into a more general conversation on a breadcrumb system. I know that as part of @panchovm's IA work he's put a lot of thought into this. So with a new issue, or an updating of 255, plus a rename of "Mobile", I think we can probably close this tracking issue. What do you think?

**Comment by fcoveram** [comment]
I posted an idea ([wporg-main-2022#255](https://github.com/WordPress/wporg-main-2022/issues/255#issuecomment-1525772331)) for the header that covers, at different extends, the following points:

* When the specific page is white, the wayfinding doesn’t work and sections/pages aren’t marked.
* Headings and breadcrumbs and subnavs aren’t consistent or connected across pages. We’ll address these per section/page.
* When in /developers for example, the nav changes slightly.
* (Mobile) When a category is active (ie:Learn), the whole category of nav instances move position.
* (Mobile) The behavior of active instances isn’t consistent (ie: Get WP vs Learn WP).

**Comment by ryelle** [comment]
> I'm seeing the old dotted focus style when I initially open the menu on mobile:

Ah, this only happens on classic themes due to an inherited style. Opened https://github.com/WordPress/wporg-mu-plugins/issues/394.

> So with a new issue, or an updating of 255, plus a rename of "Mobile"

#255 is About-specific, but for updating that local nav bar pattern globally, I'll create an issue in [wporg-parent-2021](https://github.com/WordPress/wporg-parent-2021/).

I think all the global nav updates can be tracked in https://github.com/WordPress/wporg-mu-plugins/issues/360, since the organization of pages will probably impact the interaction pattern (and vice-versa). That issue and https://github.com/WordPress/wporg-mu-plugins/issues/364 need content (or design?) owners who can make final decisions.

> I think we can probably close this tracking issue

Agreed.

**Comment by jasmussen** [comment]
> There’s duplication of nav instances (ie: Download&Extend, Get WP, and Get WP), while the footer doesn’t have it. Worth revising through the IA exercise.

Many of the items, including this one, refer to the IA exercise. @fcoveram I know you sketched out some wireframes for primary and secondary navigation. I wonder if the footer and some of the taxonomy-changes to the top menu items (Extend instead of Download & Extend, perhaps a new top level Showcase menu item to coincide with a relaunch) and links in the footer would be good to extract into a separate issue with wireframe sketches? 

>  Certain instances are verbally obscure. Revise naming conventions (ie: Mobile versus Get Apps or WordPress Apps).

If nothing is blocking us from doing it, I think we should just go ahead and rename the "Mobile" link to "WordPress Apps" as a starting point. We don't need to change the slug, so the rename should be simple.

**Comment by StevenDufresne** [comment]
> If nothing is blocking us from doing it, I think we should just go ahead and rename the "Mobile" link to "WordPress Apps" as a starting point. We don't need to change the slug, so the rename should be simple.

To be honest I don't understand the pluralization here, although it's inline with the content. 🤔

**Comment by jasmussen** [comment]
Well there are apps for both Android and iOS, hence the pluralization. I could see households that use both platforms, and would look for apps, so I'd personally be more confused by the singular. What do you think?

**Comment by ryelle** [comment]
There's already some discussion about renaming Mobile on https://github.com/WordPress/wporg-mu-plugins/issues/360, can we keep the conversation there? I'm going to close this tracking issue since we seemed to be [in agreement last week](https://github.com/WordPress/wporg-main-2022/issues/221#issuecomment-1529790968).
